### PR TITLE
Add option to exclude drives from max temp calculations

### PR DESCRIPTION
**Pull request by andreiio**
Allow users to individually exclude drives from autofan's highest temperature calculations through a dropdown in the FanSettings page, like in the attached screenshot.

This is useful for users that don't have their SSDs or any other drives behind a fan, as it prevents fans from revving up unnecessarily.

Built and tested on unRAID 6.3.3.

screenshot

_Also fixed a minor typo_

### CODE REVIEW

**Comment by bergware** [comment]
Thanks, I'll have a look.

**Comment by syntactic-salt** [comment]
@bergware this looks like a pretty good feature. If you don't mind, can I ask why this never got merged?

**Comment by bergware** [comment]
It is an interesting feature, but I didn't have time to come back to this. Meanwhile some other changes are proposed as well, resulting in a conflict.

I'll work on this to get it integrated.

**Comment by bergware** [comment]
New version is available which includes exclude disks option.

**Comment by syntactic-salt** [comment]
Thanks for doing that.

**Pull request closed without merging**
