### PR TITLE
New cache_dirs version, fixed disk_mounted script, added unused logro…

### PR DESCRIPTION
**Pull request by arberg**
Disk_mounted: This is wrong, sence $cfg is undefined, I reverted some of script

[[ -e $cfg ]] && cfg=/boot/config/plugins/$plugin/$plugin.cfg || cfg=/usr/local/emhttp/plugins/$plugin/default.cfg

### CODE REVIEW

**Comment by arberg** [comment]
I was in a hurry, hence the short message. I've also added some options to the script and updated the page. The new script also has a diagnostics option that collects and zip diagnostics. It would be cool if that could be included in the unraid diagnostics, but I think not. If you feel like it you can add a diagnostics button, which runs "cache_dirs -L" and collects the diagnostics zip from the executing directory and downloads to users browser. Or we could just run the script with the -L option from a user entered location or put it directly in /boot/logs.

The diagnostics is most interesting if user has run cache_dirs with logs enabled. But its easy enough to just ask users to do manually, and we might never need it again.

**Comment by bergware** [comment]
Thanks for the update.
I am a little short on time at the moment, but once time permits I'll make an update. And see if/how diagnostics fits in.

**Comment by arberg** [comment]
bergware you might wanna keep the changes to plg regarding links and logrotate. Of cause the release-link should be discarded.

**Comment by bergware** [comment]
Should I go ahead and merge, or you want me to wait a little longer?

**Comment by arberg** [comment]
I missed your comment. I think now would be a good time to merge. I suspect its stable now with few future edits. 

I chose to release via releases-tab following this checklist, but you just do what you want, below is more manually heavy than what you are doing as it is now:

Bump Version in cache_dirs script
Build txz archive
Update MD5 in plugin
Update releasetag in plugin
Commit but do not push (to avoid plg update on master)
Tag with cache_dirs version 'cache_dirs_2.2.3' (MUST match releasetag entry in plugin)
Push tag
Github: Edit tag, upload txz for release
Push master (then people get update)

**Comment by bergware** [comment]
I have merged your updates

**Pull request closed without merging**
